apiVersion: v1
kind: PersistentVolume
metadata:
  name: comments-volume
spec:
  storageClassName: comments
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comments-volume
spec:
  storageClassName: comments
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi